export const chandigarhAreas = [
  "Chandigarh",
  "Sector 1 Chandigarh",
  "Sector 2 Chandigarh",
  "Sector 3 Chandigarh",
  "Sector 4 Chandigarh",
  "Sector 5 Chandigarh",
  "Sector 6 Chandigarh",
  "Sector 7 Chandigarh",
  "Sector 8 Chandigarh",
  "Sector 9 Chandigarh",
  "Sector 10 Chandigarh",
  "Sector 11 Chandigarh",
  "Sector 12 Chandigarh",
  "Sector 14 Chandigarh",
  "Sector 15 Chandigarh",
  "Sector 16 Chandigarh",
  "Sector 17 Chandigarh",
  "Sector 18 Chandigarh",
  "Sector 19 Chandigarh",
  "Sector 20 Chandigarh",
  "Sector 21 Chandigarh",
  "Sector 22 Chandigarh",
  "Sector 23 Chandigarh",
  "Sector 24 Chandigarh",
  "Sector 25 Chandigarh",
  "Sector 26 Chandigarh",
  "Sector 27 Chandigarh",
  "Sector 28 Chandigarh",
  "Sector 29 Chandigarh",
  "Sector 30 Chandigarh",
  "Sector 31 Chandigarh",
  "Sector 32 Chandigarh",
  "Sector 33 Chandigarh",
  "Sector 34 Chandigarh",
  "Sector 35 Chandigarh",
  "Sector 36 Chandigarh",
  "Sector 37 Chandigarh",
  "Sector 38 Chandigarh",
  "Sector 39 Chandigarh",
  "Sector 40 Chandigarh",
  "Sector 41 Chandigarh",
  "Sector 42 Chandigarh",
  "Sector 43 Chandigarh",
  "Sector 44 Chandigarh",
  "Sector 45 Chandigarh",
  "Sector 46 Chandigarh",
  "Sector 47 Chandigarh",
  "Sector 48 Chandigarh",
  "Sector 49 Chandigarh",
  "Sector 50 Chandigarh",
  "Sector 51 Chandigarh",
  "Sector 52 Chandigarh",
  "Sector 53 Chandigarh",
  "Sector 54 Chandigarh",
  "Sector 55 Chandigarh",
  "Sector 56 Chandigarh",
  "Sector 61 Chandigarh",
  "Sector 63 Chandigarh",
  "Manimajra",
  "Daria",
  "Hallomajra",
  "Maloya",
  "Dhanas",
  "Khuda Lahora",
  "Khuda Jassu",
  "Kaimbwala",
  "Kishangarh Chandigarh",
  "Industrial Area Phase 1 Chandigarh",
  "Industrial Area Phase 2 Chandigarh",
  "IT Park Chandigarh",
  "Madhya Marg",
  "Dakshin Marg",
  "Zirakpur",
  "VIP Road Zirakpur",
  "Dhakoli",
  "Peer Muchalla",
  "Baltana",
  "Lohgarh Zirakpur",
  "Gazipur Zirakpur",
  "Patiala Road Zirakpur",
  "Ambala Highway Zirakpur",
  "Aerocity Mohali",
  "Mohali",
  "SAS Nagar",
  "Phase 1 Mohali",
  "Phase 2 Mohali",
  "Phase 3A Mohali",
  "Phase 3B1 Mohali",
  "Phase 3B2 Mohali",
  "Phase 4 Mohali",
  "Phase 5 Mohali",
  "Phase 6 Mohali",
  "Phase 7 Mohali",
  "Phase 8 Mohali",
  "Phase 9 Mohali",
  "Phase 10 Mohali",
  "Phase 11 Mohali",
  "Sector 66 Mohali",
  "Sector 67 Mohali",
  "Sector 68 Mohali",
  "Sector 69 Mohali",
  "Sector 70 Mohali",
  "Sector 71 Mohali",
  "Sector 74 Mohali",
  "Sector 75 Mohali",
  "Sector 76 Mohali",
  "Sector 77 Mohali",
  "Sector 78 Mohali",
  "Sector 79 Mohali",
  "Sector 80 Mohali",
  "Sector 82 Mohali",
  "Sector 83 Mohali",
  "Sector 85 Mohali",
  "Sector 88 Mohali",
  "Sector 89 Mohali",
  "Sector 91 Mohali",
  "Sector 92 Mohali",
  "Sector 94 Mohali",
  "Sector 105 Mohali",
  "Sector 109 Mohali",
  "Sector 110 Mohali",
  "Sector 111 Mohali",
  "Sector 114 Mohali",
  "Sector 115 Mohali",
  "Sector 116 Mohali",
  "Sector 117 Mohali",
  "Kharar",
  "Sunny Enclave",
  "Landran",
  "Desumajra",
  "Mundi Kharar",
  "Kurali",
  "Gharuan",
  "New Chandigarh",
  "Mullanpur",
  "Omaxe New Chandigarh",
  "Eco City New Chandigarh",
  "Panchkula",
  "Sector 2 Panchkula",
  "Sector 4 Panchkula",
  "Sector 5 Panchkula",
  "Sector 6 Panchkula",
  "Sector 7 Panchkula",
  "Sector 8 Panchkula",
  "Sector 9 Panchkula",
  "Sector 10 Panchkula",
  "Sector 11 Panchkula",
  "Sector 12 Panchkula",
  "Sector 12A Panchkula",
  "Sector 14 Panchkula",
  "Sector 15 Panchkula",
  "Sector 16 Panchkula",
  "Sector 17 Panchkula",
  "Sector 18 Panchkula",
  "Sector 19 Panchkula",
  "Sector 20 Panchkula",
  "Sector 21 Panchkula",
  "Sector 23 Panchkula",
  "Sector 24 Panchkula",
  "Sector 25 Panchkula",
  "Sector 26 Panchkula",
  "Sector 27 Panchkula",
  "Sector 28 Panchkula",
  "MDC Panchkula",
  "Mansa Devi Complex",
  "Pinjore",
  "Kalka",
  "Chandimandir",
  "Ramgarh Panchkula",
  "Peer Muchalla Panchkula",
  "Tribune Colony",
  "Nayagaon",
  "Kansal",
  "Zirakpur Tricity",
  "Mohali Tricity",
  "Panchkula Tricity",
  "Nearby Chandigarh Tricity Locations",
] as const;
