export const ahmedabadAreaGroups = [
  {
    region: "Central Ahmedabad",
    areas: [
      "Ashram Road",
      "C G Road",
      "Ellis Bridge",
      "Navrangpura",
      "Paldi",
      "Khanpur",
      "Bhadra",
      "Kalupur",
      "Raipur",
      "Dariapur",
      "Shahpur",
      "Jamalpur",
      "Khamasa",
      "Madhupura",
      "Sarangpur",
    ],
  },
  {
    region: "West Ahmedabad",
    areas: [
      "Ambawadi",
      "Bodakdev",
      "Vastrapur",
      "Satellite",
      "Prahlad Nagar",
      "Jodhpur",
      "Shyamal",
      "Memnagar",
      "Gurukul",
      "Naranpura",
      "Vasna",
      "Vejalpur",
      "Jivraj Park",
      "Gulbai Tekra",
      "Nehrunagar",
    ],
  },
  {
    region: "Premium & Corporate Areas",
    areas: [
      "S G Highway",
      "Sindhu Bhavan Road",
      "Thaltej",
      "Thaltej Road",
      "Science City",
      "Sola",
      "Sola Road",
      "Bopal",
      "South Bopal",
      "Ambli",
      "Ambli Bopal Road",
      "Shela",
      "Shilaj",
      "Gota",
      "Vaishno Devi",
      "SP Ring Road",
    ],
  },
  {
    region: "North Ahmedabad",
    areas: [
      "Chandkheda",
      "Motera",
      "Sabarmati",
      "Ranip",
      "New Ranip",
      "Chandlodia",
      "Ghatlodia",
      "Tragad",
      "Jagatpur",
      "Ognaj",
      "Chenpur",
      "Keshav Nagar",
      "Usmanpura",
    ],
  },
  {
    region: "East Ahmedabad",
    areas: [
      "Maninagar",
      "Kankaria",
      "Bapunagar",
      "Naroda",
      "Nava Naroda",
      "Nikol",
      "Odhav",
      "Vastral",
      "Amraiwadi",
      "Khokhra",
      "Hatkeshwar",
      "Rakhial",
      "Gomtipur",
      "Saraspur",
      "Ghodasar",
      "Isanpur",
      "Ramol",
    ],
  },
  {
    region: "South Ahmedabad",
    areas: [
      "Narol",
      "Narolgam",
      "Vatva",
      "Vatva GIDC",
      "Lambha",
      "Aslali",
      "Hathijan",
      "Jashoda Nagar",
      "Dani Limbada",
      "Behrampura",
      "Shah E Alam Roja",
      "Gita Mandir",
      "Vishala",
    ],
  },
  {
    region: "Ahmedabad Outskirts",
    areas: [
      "Sanand",
      "Sanathal",
      "Changodar",
      "Bavla",
      "Dholka",
      "Dholera",
      "Sarkhej",
      "Shantipura",
      "Kathwada",
      "Naroda GIDC",
      "Barejadi",
      "Mahemdabad",
      "Kheda",
      "Viramgam",
      "Bagodara",
    ],
  },
];
