export const jaipurAreas = [
  "Vaishali Nagar",
  "Mansarovar",
  "Malviya Nagar",
  "Jagatpura",
  "Ajmer Road",
  "Tonk Road",
  "Pratap Nagar",
  "Jhotwara",
  "Sanganer",
  "C-Scheme",
  "Raja Park",
  "Kalwar Road",
  "Gopalpura By Pass",
  "Gokulpura",
  "Patrakar Colony",
  "New Sanganer Road",
  "Sodala",
  "Nirman Nagar",
  "Durgapura",
  "Sirsi Road",
  "Sikar Road",
  "Agra Road",
  "Khatipura",
  "Jaisinghpura",
  "Tonk Phatak",
  "Jawahar Nagar",
  "Shyam Nagar",
  "Gandhi Path",
  "Vidhyadhar Nagar",
  "Bani Park",
  "Chitrakoot",
  "Civil Lines",
  "Sitapura",
  "Bapu Nagar",
  "Jaipur-Ajmer Express Highway",
  "Tilak Nagar",
  "Gopalpura",
  "Kanakpura",
  "Moti Dongri Road",
  "Niwaru",
  "Alwar Highway",
  "Shastri Nagar",
  "Mahaveer Nagar",
  "Adarsh Nagar",
  "Lal Kothi",
  "Anand Nagar",
  "Ambabari",
  "Benad Road",
  "Narayan Vihar",
  "Jyoti Nagar",
  "Sardar Patel Marg",
  "Sidharth Nagar",
  "Govindpura",
  "Kanota",
  "Shankar Nagar",
  "Muralipura",
  "Ramnagar",
  "Mahapura",
  "Muhana",
  "Pahadiya Road",
  "Shanti Nagar",
  "Virat Nagar",
  "Vishwakarma Industrial Area",
  "Sahakar Marg",
  "Nehru Nagar",
  "Budhsinghpura",
  "Bais Godam",
  "Kukas",
  "Jhotwara Road",
  "Triveni Nagar",
  "Amer",
  "Jobner",
  "Pink City",
  "Govind Nagar",
  "Chokhi Dhani",
  "Sector-26",
  "Delhi-Jaipur expressway",
  "Goner Road",
  "Sethi Colony",
  "Phulera",
  "Kalwara",
  "Renwal Manji",
  "Bhankrota",
  "Bagru",
  "Renwal Phagi Road",
  "Subhash Marg",
  "Ashok Nagar",
  "Vatika",
  "Bhawani Singh Road",
  "Diggi Road",
  "Sachivalaya Nagar",
  "NH-8",
  "Shivdaspura",
  "Hanuman Nagar",
  "NH-12",
  "Mahal Road",
  "Sindhi Camp",
  "Shiprapath",
  "Dudu",
  "Chomu",
  "Brahmpuri",
  "Kotputli",
  "Shiv Nagar",
  "Lalarpura",
  "Bindayaka",
  "Mahalan Ajmer Road",
  "Transport Nagar",
  "Nari Ka Bas",
  "Lajpat Marg",
  "Anand Lok",
  "Parthviraj Nagar",
  "SC Road",
  "Jalupura",
  "Sahdev Marg",
  "Padampura",
  "Gopalbari",
  "Tagore Nagar",
  "Milap Nagar",
  "Takht E Shahi Road",
  "Vivekanand Marg",
  "Malpura",
  "Dausa",
  "Shahpura",
  "RIICO Industrial Area",
  "Baroni",
  "Raj Bhavan Road",
  "Sagram Colony",
  "Udyog Nagar",
  "M I Road",
  "Boraj",
  "Heerawala",
  "Bhan Nagar",
  "Officers Campus Colony",
  "Marudhar Nagar",
  "Bichun",
  "Niwai",
  "Achrol",
  "Saiwad",
  "Asalpur",
  "Chaksu",
  "Bhojpura",
  "Chirnotiya",
  "Simliya Road",
  "Roop Vihar Colony",
  "Palsana Road",
  "Tilawala",
  "Anita Colony",
  "Purani Basti",
  "Paldi Meena",
  "Girdharipura",
  "Hathroi",
  "Ghati Karolan",
  "Brijlalpura",
  "Sanjay Nagar",
  "Dantri",
  "Jamwa Ramgarh",
  "Moti Nagar",
  "Kanwar Nagar",
  "Ramganj",
  "Jaswant Nagar",
  "Arjun Nagar",
  "Sawarda",
  "Bassi",
  "Jamdoli",
  "Bajaj Nagar",
  "Hasanpura",
  "Govindpuri",
  "Dholai",
  "Subhash Nagar",
  "Mandha",
  "JLN Marg",
  "Ajairajpura",
  "Jharna",
  "Karolan Ka Barh",
  "Surya Nagar",
  "Maruti Nagar",
  "Doongri",
  "Amrapali Circle",
  "Jairampura",
  "Ramsinghpura",
  "Shikarpura",
  "Sarna Doongar",
  "Boytawala",
  "Keshar Vihar",
  "Manoharpura",
  "Bagrana",
  "Mangarh Khokhawala",
  "Naradpura",
  "Laxmi Narayan Puri",
  "Nandlalpura",
  "Madhorajpura - Chandma Road",
  "Chittora",
  "Bhambori",
  "Sunder Nagar",
  "Ganatpura",
  "Phagi Road",
] as const;
